window.WISHORA_CATALOG = {
  "occasions": [
    {
      "id": "birthday",
      "emoji": "🎂",
      "label": "Birthday",
      "description": "Make their birthday feel like its own little world.",
      "matches": [
        "birthday",
        "cake",
        "party",
        "age"
      ]
    },
    {
      "id": "anniversary",
      "emoji": "💍",
      "label": "Anniversary",
      "description": "Turn your story, memories and milestones into an interactive keepsake.",
      "matches": [
        "anniversary",
        "love",
        "couple",
        "years",
        "romance"
      ]
    },
    {
      "id": "wedding",
      "emoji": "❤️",
      "label": "Wedding",
      "description": "A beautiful digital celebration for the couple, family or guests.",
      "matches": [
        "wedding",
        "bride",
        "groom",
        "vows",
        "marriage"
      ]
    },
    {
      "id": "baby-shower",
      "emoji": "👶",
      "label": "Baby Shower",
      "description": "Celebrate the parents-to-be with photos, wishes and tiny surprises.",
      "matches": [
        "baby",
        "shower",
        "mama",
        "parents",
        "little one"
      ]
    },
    {
      "id": "graduation",
      "emoji": "🎓",
      "label": "Graduation",
      "description": "Celebrate the hard work, the memories and the next chapter.",
      "matches": [
        "graduation",
        "graduate",
        "class",
        "degree",
        "cap"
      ]
    },
    {
      "id": "congratulations",
      "emoji": "🎊",
      "label": "Congratulations",
      "description": "Give a big achievement the celebration it deserves.",
      "matches": [
        "congratulations",
        "achievement",
        "success",
        "milestone",
        "proud"
      ]
    },
    {
      "id": "farewell",
      "emoji": "💐",
      "label": "Farewell",
      "description": "A heartfelt digital goodbye packed with memories and good wishes.",
      "matches": [
        "farewell",
        "goodbye",
        "voyage",
        "leaving",
        "memories"
      ]
    },
    {
      "id": "housewarming",
      "emoji": "🏡",
      "label": "Housewarming",
      "description": "Welcome a new home with a warm, personal celebration.",
      "matches": [
        "housewarming",
        "home",
        "house",
        "new home",
        "welcome"
      ]
    },
    {
      "id": "festival-wishes",
      "emoji": "🪔",
      "label": "Festival Wishes",
      "description": "Create a festive page for family, friends, teams or communities.",
      "matches": [
        "festival",
        "diwali",
        "christmas",
        "eid",
        "holi",
        "pongal",
        "sankranti",
        "new year",
        "raksha bandhan"
      ]
    },
    {
      "id": "custom",
      "emoji": "🎁",
      "label": "Custom Occasion",
      "description": "Start with a blank canvas and build exactly the celebration you imagine.",
      "matches": [
        "custom",
        "special",
        "surprise",
        "anything"
      ]
    }
  ],
  "products": [
    {
      "slug": "wishora-birthday-classic",
      "id": "wishora-birthday-classic",
      "name": "Classic Confetti Birthday",
      "blurb": "A bright, joyful birthday story with candles, memories and a final burst of celebration.",
      "includes": [
        "Cover",
        "Cake / Gift",
        "Photos",
        "Memories",
        "Letter"
      ],
      "occasion": "Birthday",
      "occasionId": "birthday",
      "engine": "birthday",
      "variant": "classic",
      "photoLimit": 4,
      "palette": "lemon",
      "cover": "images/templates/wishora-birthday-classic/hero.svg",
      "pages": [
        "cover",
        "dedication",
        "cake",
        "photos",
        "memories",
        "song",
        "quiz",
        "letter",
        "surprise",
        "fireworks"
      ],
      "sections": [
        "cover",
        "dedication",
        "cake",
        "photos",
        "memories",
        "song",
        "quiz",
        "letter",
        "surprise",
        "fireworks"
      ],
      "defaults": {
        "recipient": "",
        "sender": "",
        "passcode": "",
        "passcodeProtected": true,
        "occasionLabel": "Birthday",
        "title": "",
        "letter": "",
        "date": "",
        "songTitle": "",
        "songArtist": "",
        "movieTitle": "",
        "movieTagline": "",
        "memories": [],
        "promises": [],
        "photos": [],
        "theme": "lemon",
        "sections": [
          "cover",
          "dedication",
          "cake",
          "photos",
          "memories",
          "song",
          "quiz",
          "letter",
          "surprise",
          "fireworks"
        ],
        "birthdayRevealWords": [
          "Your",
          "birthday",
          "surprise",
          "awaits"
        ],
        "birthdayNoMessage": "The surprise is waiting… click Yes when you are ready! ✨",
        "birthdayWishPrompt": "Close your eyes and make a wish ✨",
        "birthdayBouquetMessages": [
          "A little love for you",
          "A little joy for today",
          "A memory worth keeping",
          "Wishing you a beautiful year ahead"
        ],
        "birthdayGiftPrompt": "One last little surprise…",
        "birthdayGiftMessage": "Your personalized surprise will appear here.",
        "birthdayFinalMessage": "Happy Birthday ✨",
        "quizQuestion": "",
        "surpriseMessage": "",
        "festivalName": "",
        "audioData": "",
        "videoData": "",
        "audioDataName": "",
        "videoDataName": ""
      },
      "popularity": "new",
      "templateRole": "customizable-blueprint"
    },
    {
      "slug": "wishora-birthday-gift",
      "id": "wishora-birthday-gift",
      "name": "Open Your Birthday Gift",
      "blurb": "A playful gift-box experience that reveals your message and favourite memories.",
      "includes": [
        "Cover",
        "Cake / Gift",
        "Photos",
        "Memories",
        "Letter"
      ],
      "occasion": "Birthday",
      "occasionId": "birthday",
      "engine": "giftbox",
      "variant": "gift",
      "photoLimit": 4,
      "palette": "lemon",
      "cover": "images/templates/wishora-birthday-gift/hero.svg",
      "pages": [
        "cover",
        "dedication",
        "giftbox",
        "photos",
        "song",
        "letter",
        "quiz",
        "certificate",
        "surprise",
        "fireworks"
      ],
      "sections": [
        "cover",
        "dedication",
        "giftbox",
        "photos",
        "song",
        "letter",
        "quiz",
        "certificate",
        "surprise",
        "fireworks"
      ],
      "defaults": {
        "recipient": "",
        "sender": "",
        "passcode": "",
        "passcodeProtected": true,
        "occasionLabel": "Birthday",
        "title": "",
        "letter": "",
        "date": "",
        "songTitle": "",
        "songArtist": "",
        "movieTitle": "",
        "movieTagline": "",
        "memories": [],
        "promises": [],
        "photos": [],
        "theme": "lemon",
        "sections": [
          "cover",
          "dedication",
          "giftbox",
          "photos",
          "song",
          "letter",
          "quiz",
          "certificate",
          "surprise",
          "fireworks"
        ],
        "quizQuestion": "",
        "surpriseMessage": "",
        "festivalName": "",
        "birthdayRevealWords": [
          "Something",
          "special",
          "is",
          "waiting"
        ],
        "birthdayNoMessage": "Not yet? The surprise is waiting! ✨",
        "birthdayWishPrompt": "Make a wish before you open your gift ✨",
        "birthdayBouquetMessages": [
          "A little joy for you",
          "A little sparkle for today",
          "More memories to come",
          "Wishing you the very best"
        ],
        "birthdayGiftPrompt": "Open your birthday gift",
        "birthdayGiftMessage": "Your personalized gift message will appear here.",
        "birthdayFinalMessage": "Your birthday surprise ✨",
        "audioData": "",
        "videoData": "",
        "audioDataName": "",
        "videoDataName": ""
      },
      "popularity": "standard",
      "templateRole": "customizable-blueprint"
    },
    {
      "slug": "wishora-anniversary-story",
      "id": "wishora-anniversary-story",
      "name": "Our Love Story",
      "blurb": "A romantic chapter-by-chapter timeline of the moments that became your story.",
      "includes": [
        "Cover",
        "Photos",
        "Story Timeline",
        "Letter",
        "Song / Video"
      ],
      "occasion": "Anniversary",
      "occasionId": "anniversary",
      "engine": "museum",
      "variant": "story",
      "photoLimit": 6,
      "palette": "blush",
      "cover": "images/templates/wishora-anniversary-story/hero.svg",
      "pages": [
        "cover",
        "dedication",
        "photos",
        "timeline",
        "memories",
        "letter",
        "song",
        "quiz",
        "surprise",
        "fireworks"
      ],
      "sections": [
        "cover",
        "dedication",
        "photos",
        "timeline",
        "memories",
        "letter",
        "song",
        "quiz",
        "surprise",
        "fireworks"
      ],
      "defaults": {
        "recipient": "",
        "sender": "",
        "passcode": "",
        "passcodeProtected": true,
        "occasionLabel": "Anniversary",
        "title": "",
        "letter": "",
        "date": "",
        "songTitle": "",
        "songArtist": "",
        "movieTitle": "",
        "movieTagline": "",
        "memories": [],
        "promises": [],
        "photos": [],
        "theme": "blush",
        "sections": [
          "cover",
          "dedication",
          "photos",
          "timeline",
          "memories",
          "letter",
          "song",
          "quiz",
          "surprise",
          "fireworks"
        ],
        "quizQuestion": "",
        "surpriseMessage": "",
        "festivalName": "",
        "audioData": "",
        "videoData": "",
        "audioDataName": "",
        "videoDataName": ""
      },
      "popularity": "popular",
      "templateRole": "customizable-blueprint"
    },
    {
      "slug": "wishora-anniversary-cinema",
      "id": "wishora-anniversary-cinema",
      "name": "Our Anniversary Film",
      "blurb": "A cinematic keepsake built for your photos, story and favourite soundtrack.",
      "includes": [
        "Cover",
        "Photos",
        "Story Timeline",
        "Letter",
        "Song / Video"
      ],
      "occasion": "Anniversary",
      "occasionId": "anniversary",
      "engine": "cinema",
      "variant": "cinema",
      "photoLimit": 6,
      "palette": "blush",
      "cover": "images/templates/wishora-anniversary-cinema/hero.svg",
      "pages": [
        "cover",
        "dedication",
        "video",
        "photos",
        "timeline",
        "letter",
        "song",
        "surprise",
        "memories",
        "fireworks"
      ],
      "sections": [
        "cover",
        "dedication",
        "video",
        "photos",
        "timeline",
        "letter",
        "song",
        "surprise",
        "memories",
        "fireworks"
      ],
      "defaults": {
        "recipient": "",
        "sender": "",
        "passcode": "",
        "passcodeProtected": true,
        "occasionLabel": "Anniversary",
        "title": "",
        "letter": "",
        "date": "",
        "songTitle": "",
        "songArtist": "",
        "movieTitle": "",
        "movieTagline": "",
        "memories": [],
        "promises": [],
        "photos": [],
        "theme": "blush",
        "sections": [
          "cover",
          "dedication",
          "video",
          "photos",
          "timeline",
          "letter",
          "song",
          "surprise",
          "memories",
          "fireworks"
        ],
        "quizQuestion": "",
        "surpriseMessage": "",
        "festivalName": "",
        "audioData": "",
        "videoData": "",
        "audioDataName": "",
        "videoDataName": ""
      },
      "popularity": "standard",
      "templateRole": "customizable-blueprint"
    },
    {
      "slug": "wishora-wedding-story",
      "id": "wishora-wedding-story",
      "name": "Our Wedding Story",
      "blurb": "A polished wedding keepsake for the couple, with moments, words and music.",
      "includes": [
        "Cover",
        "Photos",
        "Wedding Vows",
        "Timeline",
        "Letter"
      ],
      "occasion": "Wedding",
      "occasionId": "wedding",
      "engine": "museum",
      "variant": "story",
      "photoLimit": 8,
      "palette": "cocoa",
      "cover": "images/templates/wishora-wedding-story/hero.svg",
      "pages": [
        "cover",
        "dedication",
        "photos",
        "timeline",
        "wedding-vows",
        "letter",
        "song",
        "guestbook",
        "surprise",
        "fireworks"
      ],
      "sections": [
        "cover",
        "dedication",
        "photos",
        "timeline",
        "wedding-vows",
        "letter",
        "song",
        "guestbook",
        "surprise",
        "fireworks"
      ],
      "defaults": {
        "recipient": "",
        "sender": "",
        "passcode": "",
        "passcodeProtected": true,
        "occasionLabel": "Wedding",
        "title": "",
        "letter": "",
        "date": "",
        "songTitle": "",
        "songArtist": "",
        "movieTitle": "",
        "movieTagline": "",
        "memories": [],
        "promises": [],
        "photos": [],
        "theme": "cocoa",
        "sections": [
          "cover",
          "dedication",
          "photos",
          "timeline",
          "wedding-vows",
          "letter",
          "song",
          "guestbook",
          "surprise",
          "fireworks"
        ],
        "quizQuestion": "",
        "surpriseMessage": "",
        "festivalName": "",
        "audioData": "",
        "videoData": "",
        "audioDataName": "",
        "videoDataName": ""
      },
      "popularity": "standard",
      "templateRole": "customizable-blueprint"
    },
    {
      "slug": "wishora-wedding-vows",
      "id": "wishora-wedding-vows",
      "name": "Wedding Vows & Memories",
      "blurb": "A vow-forward experience for the couple, surrounded by favourite photographs.",
      "includes": [
        "Cover",
        "Photos",
        "Wedding Vows",
        "Timeline",
        "Letter"
      ],
      "occasion": "Wedding",
      "occasionId": "wedding",
      "engine": "letters",
      "variant": "vows",
      "photoLimit": 6,
      "palette": "cocoa",
      "cover": "images/templates/wishora-wedding-vows/hero.svg",
      "pages": [
        "cover",
        "dedication",
        "wedding-vows",
        "photos",
        "timeline",
        "promises",
        "letter",
        "guestbook",
        "song",
        "fireworks"
      ],
      "sections": [
        "cover",
        "dedication",
        "wedding-vows",
        "photos",
        "timeline",
        "promises",
        "letter",
        "guestbook",
        "song",
        "fireworks"
      ],
      "defaults": {
        "recipient": "",
        "sender": "",
        "passcode": "",
        "passcodeProtected": true,
        "occasionLabel": "Wedding",
        "title": "",
        "letter": "",
        "date": "",
        "songTitle": "",
        "songArtist": "",
        "movieTitle": "",
        "movieTagline": "",
        "memories": [],
        "promises": [],
        "photos": [],
        "theme": "cocoa",
        "sections": [
          "cover",
          "dedication",
          "wedding-vows",
          "photos",
          "timeline",
          "promises",
          "letter",
          "guestbook",
          "song",
          "fireworks"
        ],
        "quizQuestion": "",
        "surpriseMessage": "",
        "festivalName": "",
        "audioData": "",
        "videoData": "",
        "audioDataName": "",
        "videoDataName": ""
      },
      "popularity": "popular",
      "templateRole": "customizable-blueprint"
    },
    {
      "slug": "wishora-baby-shower-welcome",
      "id": "wishora-baby-shower-welcome",
      "name": "Welcome, Little One",
      "blurb": "A soft, joyful baby-shower page for family and friends to share wishes.",
      "includes": [
        "Cover",
        "Baby Wishes",
        "Photos",
        "Timeline",
        "Letter"
      ],
      "occasion": "Baby Shower",
      "occasionId": "baby-shower",
      "engine": "minisite",
      "variant": "welcome",
      "photoLimit": 6,
      "palette": "sky",
      "cover": "images/templates/wishora-baby-shower-welcome/hero.svg",
      "pages": [
        "cover",
        "dedication",
        "baby-wishes",
        "photos",
        "timeline",
        "letter",
        "wishes",
        "guestbook",
        "surprise",
        "fireworks"
      ],
      "sections": [
        "cover",
        "dedication",
        "baby-wishes",
        "photos",
        "timeline",
        "letter",
        "wishes",
        "guestbook",
        "surprise",
        "fireworks"
      ],
      "defaults": {
        "recipient": "",
        "sender": "",
        "passcode": "",
        "passcodeProtected": true,
        "occasionLabel": "Baby Shower",
        "title": "",
        "letter": "",
        "date": "",
        "songTitle": "",
        "songArtist": "",
        "movieTitle": "",
        "movieTagline": "",
        "memories": [],
        "promises": [],
        "photos": [],
        "theme": "sky",
        "sections": [
          "cover",
          "dedication",
          "baby-wishes",
          "photos",
          "timeline",
          "letter",
          "wishes",
          "guestbook",
          "surprise",
          "fireworks"
        ],
        "quizQuestion": "",
        "surpriseMessage": "",
        "festivalName": "",
        "audioData": "",
        "videoData": "",
        "audioDataName": "",
        "videoDataName": ""
      },
      "popularity": "new",
      "templateRole": "customizable-blueprint"
    },
    {
      "slug": "wishora-baby-shower-game",
      "id": "wishora-baby-shower-game",
      "name": "Guess the Baby Game",
      "blurb": "A playful shower experience with a mini quiz, photos and reveal message.",
      "includes": [
        "Cover",
        "Baby Wishes",
        "Photos",
        "Timeline",
        "Letter"
      ],
      "occasion": "Baby Shower",
      "occasionId": "baby-shower",
      "engine": "yesno",
      "variant": "game",
      "photoLimit": 4,
      "palette": "sky",
      "cover": "images/templates/wishora-baby-shower-game/hero.svg",
      "pages": [
        "cover",
        "dedication",
        "photos",
        "quiz",
        "yesno",
        "baby-wishes",
        "letter",
        "guestbook",
        "surprise",
        "fireworks"
      ],
      "sections": [
        "cover",
        "dedication",
        "photos",
        "quiz",
        "yesno",
        "baby-wishes",
        "letter",
        "guestbook",
        "surprise",
        "fireworks"
      ],
      "defaults": {
        "recipient": "",
        "sender": "",
        "passcode": "",
        "passcodeProtected": true,
        "occasionLabel": "Baby Shower",
        "title": "",
        "letter": "",
        "date": "",
        "songTitle": "",
        "songArtist": "",
        "movieTitle": "",
        "movieTagline": "",
        "memories": [],
        "promises": [],
        "photos": [],
        "theme": "sky",
        "sections": [
          "cover",
          "dedication",
          "photos",
          "quiz",
          "yesno",
          "baby-wishes",
          "letter",
          "guestbook",
          "surprise",
          "fireworks"
        ],
        "quizQuestion": "",
        "surpriseMessage": "",
        "festivalName": "",
        "audioData": "",
        "videoData": "",
        "audioDataName": "",
        "videoDataName": ""
      },
      "popularity": "popular",
      "templateRole": "customizable-blueprint"
    },
    {
      "slug": "wishora-graduation-classic",
      "id": "wishora-graduation-classic",
      "name": "Class of 2026",
      "blurb": "A bold graduation celebration with diploma, memories and a final confetti moment.",
      "includes": [
        "Cover",
        "Diploma",
        "Photos",
        "Timeline",
        "Letter"
      ],
      "occasion": "Graduation",
      "occasionId": "graduation",
      "engine": "museum",
      "variant": "classic",
      "photoLimit": 6,
      "palette": "ink",
      "cover": "images/templates/wishora-graduation-classic/hero.svg",
      "pages": [
        "cover",
        "dedication",
        "graduation-diploma",
        "photos",
        "timeline",
        "letter",
        "certificate",
        "guestbook",
        "surprise",
        "fireworks"
      ],
      "sections": [
        "cover",
        "dedication",
        "graduation-diploma",
        "photos",
        "timeline",
        "letter",
        "certificate",
        "guestbook",
        "surprise",
        "fireworks"
      ],
      "defaults": {
        "recipient": "",
        "sender": "",
        "passcode": "",
        "passcodeProtected": true,
        "occasionLabel": "Graduation",
        "title": "",
        "letter": "",
        "date": "",
        "songTitle": "",
        "songArtist": "",
        "movieTitle": "",
        "movieTagline": "",
        "memories": [],
        "promises": [],
        "photos": [],
        "theme": "ink",
        "sections": [
          "cover",
          "dedication",
          "graduation-diploma",
          "photos",
          "timeline",
          "letter",
          "certificate",
          "guestbook",
          "surprise",
          "fireworks"
        ],
        "quizQuestion": "",
        "surpriseMessage": "",
        "festivalName": "",
        "audioData": "",
        "videoData": "",
        "audioDataName": "",
        "videoDataName": ""
      },
      "popularity": "popular",
      "templateRole": "customizable-blueprint"
    },
    {
      "slug": "wishora-graduation-future",
      "id": "wishora-graduation-future",
      "name": "Next Chapter",
      "blurb": "A forward-looking graduation page with a letter, timeline and countdown to what comes next.",
      "includes": [
        "Cover",
        "Diploma",
        "Photos",
        "Timeline",
        "Letter"
      ],
      "occasion": "Graduation",
      "occasionId": "graduation",
      "engine": "minisite",
      "variant": "future",
      "photoLimit": 6,
      "palette": "ink",
      "cover": "images/templates/wishora-graduation-future/hero.svg",
      "pages": [
        "cover",
        "dedication",
        "photos",
        "timeline",
        "graduation-diploma",
        "letter",
        "wishes",
        "countdown",
        "surprise",
        "fireworks"
      ],
      "sections": [
        "cover",
        "dedication",
        "photos",
        "timeline",
        "graduation-diploma",
        "letter",
        "wishes",
        "countdown",
        "surprise",
        "fireworks"
      ],
      "defaults": {
        "recipient": "",
        "sender": "",
        "passcode": "",
        "passcodeProtected": true,
        "occasionLabel": "Graduation",
        "title": "",
        "letter": "",
        "date": "",
        "songTitle": "",
        "songArtist": "",
        "movieTitle": "",
        "movieTagline": "",
        "memories": [],
        "promises": [],
        "photos": [],
        "theme": "ink",
        "sections": [
          "cover",
          "dedication",
          "photos",
          "timeline",
          "graduation-diploma",
          "letter",
          "wishes",
          "countdown",
          "surprise",
          "fireworks"
        ],
        "quizQuestion": "",
        "surpriseMessage": "",
        "festivalName": "",
        "audioData": "",
        "videoData": "",
        "audioDataName": "",
        "videoDataName": ""
      },
      "popularity": "new",
      "templateRole": "customizable-blueprint"
    },
    {
      "slug": "wishora-congratulations-celebrate",
      "id": "wishora-congratulations-celebrate",
      "name": "You Did It!",
      "blurb": "A high-energy congratulations page with confetti, a message and memory gallery.",
      "includes": [
        "Cover",
        "Achievement",
        "Photos",
        "Certificate",
        "Letter"
      ],
      "occasion": "Congratulations",
      "occasionId": "congratulations",
      "engine": "minisite",
      "variant": "celebrate",
      "photoLimit": 6,
      "palette": "cherry",
      "cover": "images/templates/wishora-congratulations-celebrate/hero.svg",
      "pages": [
        "cover",
        "dedication",
        "congrats-confetti",
        "photos",
        "certificate",
        "letter",
        "wishes",
        "quiz",
        "surprise",
        "fireworks"
      ],
      "sections": [
        "cover",
        "dedication",
        "congrats-confetti",
        "photos",
        "certificate",
        "letter",
        "wishes",
        "quiz",
        "surprise",
        "fireworks"
      ],
      "defaults": {
        "recipient": "",
        "sender": "",
        "passcode": "",
        "passcodeProtected": true,
        "occasionLabel": "Congratulations",
        "title": "",
        "letter": "",
        "date": "",
        "songTitle": "",
        "songArtist": "",
        "movieTitle": "",
        "movieTagline": "",
        "memories": [],
        "promises": [],
        "photos": [],
        "theme": "cherry",
        "sections": [
          "cover",
          "dedication",
          "congrats-confetti",
          "photos",
          "certificate",
          "letter",
          "wishes",
          "quiz",
          "surprise",
          "fireworks"
        ],
        "quizQuestion": "",
        "surpriseMessage": "",
        "festivalName": "",
        "audioData": "",
        "videoData": "",
        "audioDataName": "",
        "videoDataName": ""
      },
      "popularity": "standard",
      "templateRole": "customizable-blueprint"
    },
    {
      "slug": "wishora-congratulations-gallery",
      "id": "wishora-congratulations-gallery",
      "name": "The Achievement Gallery",
      "blurb": "A museum-style showcase for the milestones and people behind the achievement.",
      "includes": [
        "Cover",
        "Achievement",
        "Photos",
        "Certificate",
        "Letter"
      ],
      "occasion": "Congratulations",
      "occasionId": "congratulations",
      "engine": "museum",
      "variant": "gallery",
      "photoLimit": 8,
      "palette": "cherry",
      "cover": "images/templates/wishora-congratulations-gallery/hero.svg",
      "pages": [
        "cover",
        "dedication",
        "museum",
        "photos",
        "timeline",
        "certificate",
        "letter",
        "guestbook",
        "surprise",
        "fireworks"
      ],
      "sections": [
        "cover",
        "dedication",
        "museum",
        "photos",
        "timeline",
        "certificate",
        "letter",
        "guestbook",
        "surprise",
        "fireworks"
      ],
      "defaults": {
        "recipient": "",
        "sender": "",
        "passcode": "",
        "passcodeProtected": true,
        "occasionLabel": "Congratulations",
        "title": "",
        "letter": "",
        "date": "",
        "songTitle": "",
        "songArtist": "",
        "movieTitle": "",
        "movieTagline": "",
        "memories": [],
        "promises": [],
        "photos": [],
        "theme": "cherry",
        "sections": [
          "cover",
          "dedication",
          "museum",
          "photos",
          "timeline",
          "certificate",
          "letter",
          "guestbook",
          "surprise",
          "fireworks"
        ],
        "quizQuestion": "",
        "surpriseMessage": "",
        "festivalName": "",
        "audioData": "",
        "videoData": "",
        "audioDataName": "",
        "videoDataName": ""
      },
      "popularity": "popular",
      "templateRole": "customizable-blueprint"
    },
    {
      "slug": "wishora-farewell-voyage",
      "id": "wishora-farewell-voyage",
      "name": "Bon Voyage",
      "blurb": "A warm send-off with a countdown, memories and a final message to take along.",
      "includes": [
        "Cover",
        "Farewell Toast",
        "Photos",
        "Timeline",
        "Letter"
      ],
      "occasion": "Farewell",
      "occasionId": "farewell",
      "engine": "minisite",
      "variant": "voyage",
      "photoLimit": 6,
      "palette": "sky",
      "cover": "images/templates/wishora-farewell-voyage/hero.svg",
      "pages": [
        "cover",
        "dedication",
        "farewell-toast",
        "photos",
        "timeline",
        "letter",
        "song",
        "guestbook",
        "surprise",
        "fireworks"
      ],
      "sections": [
        "cover",
        "dedication",
        "farewell-toast",
        "photos",
        "timeline",
        "letter",
        "song",
        "guestbook",
        "surprise",
        "fireworks"
      ],
      "defaults": {
        "recipient": "",
        "sender": "",
        "passcode": "",
        "passcodeProtected": true,
        "occasionLabel": "Farewell",
        "title": "",
        "letter": "",
        "date": "",
        "songTitle": "",
        "songArtist": "",
        "movieTitle": "",
        "movieTagline": "",
        "memories": [],
        "promises": [],
        "photos": [],
        "theme": "sky",
        "sections": [
          "cover",
          "dedication",
          "farewell-toast",
          "photos",
          "timeline",
          "letter",
          "song",
          "guestbook",
          "surprise",
          "fireworks"
        ],
        "quizQuestion": "",
        "surpriseMessage": "",
        "festivalName": "",
        "audioData": "",
        "videoData": "",
        "audioDataName": "",
        "videoDataName": ""
      },
      "popularity": "new",
      "templateRole": "customizable-blueprint"
    },
    {
      "slug": "wishora-farewell-memory",
      "id": "wishora-farewell-memory",
      "name": "Memory Lane Goodbye",
      "blurb": "A museum of shared moments for a friend, colleague or loved one who is leaving.",
      "includes": [
        "Cover",
        "Farewell Toast",
        "Photos",
        "Timeline",
        "Letter"
      ],
      "occasion": "Farewell",
      "occasionId": "farewell",
      "engine": "museum",
      "variant": "memory",
      "photoLimit": 8,
      "palette": "sky",
      "cover": "images/templates/wishora-farewell-memory/hero.svg",
      "pages": [
        "cover",
        "dedication",
        "museum",
        "photos",
        "memories",
        "letter",
        "wishes",
        "guestbook",
        "surprise",
        "fireworks"
      ],
      "sections": [
        "cover",
        "dedication",
        "museum",
        "photos",
        "memories",
        "letter",
        "wishes",
        "guestbook",
        "surprise",
        "fireworks"
      ],
      "defaults": {
        "recipient": "",
        "sender": "",
        "passcode": "",
        "passcodeProtected": true,
        "occasionLabel": "Farewell",
        "title": "",
        "letter": "",
        "date": "",
        "songTitle": "",
        "songArtist": "",
        "movieTitle": "",
        "movieTagline": "",
        "memories": [],
        "promises": [],
        "photos": [],
        "theme": "sky",
        "sections": [
          "cover",
          "dedication",
          "museum",
          "photos",
          "memories",
          "letter",
          "wishes",
          "guestbook",
          "surprise",
          "fireworks"
        ],
        "quizQuestion": "",
        "surpriseMessage": "",
        "festivalName": "",
        "audioData": "",
        "videoData": "",
        "audioDataName": "",
        "videoDataName": ""
      },
      "popularity": "standard",
      "templateRole": "customizable-blueprint"
    },
    {
      "slug": "wishora-housewarming-welcome",
      "id": "wishora-housewarming-welcome",
      "name": "Welcome Home",
      "blurb": "A warm housewarming greeting with a new-home message, gallery and wishes.",
      "includes": [
        "Cover",
        "Home Welcome",
        "Photos",
        "Timeline",
        "Letter"
      ],
      "occasion": "Housewarming",
      "occasionId": "housewarming",
      "engine": "minisite",
      "variant": "welcome",
      "photoLimit": 6,
      "palette": "mint",
      "cover": "images/templates/wishora-housewarming-welcome/hero.svg",
      "pages": [
        "cover",
        "dedication",
        "home-welcome",
        "photos",
        "timeline",
        "letter",
        "wishes",
        "guestbook",
        "surprise",
        "fireworks"
      ],
      "sections": [
        "cover",
        "dedication",
        "home-welcome",
        "photos",
        "timeline",
        "letter",
        "wishes",
        "guestbook",
        "surprise",
        "fireworks"
      ],
      "defaults": {
        "recipient": "",
        "sender": "",
        "passcode": "",
        "passcodeProtected": true,
        "occasionLabel": "Housewarming",
        "title": "",
        "letter": "",
        "date": "",
        "songTitle": "",
        "songArtist": "",
        "movieTitle": "",
        "movieTagline": "",
        "memories": [],
        "promises": [],
        "photos": [],
        "theme": "mint",
        "sections": [
          "cover",
          "dedication",
          "home-welcome",
          "photos",
          "timeline",
          "letter",
          "wishes",
          "guestbook",
          "surprise",
          "fireworks"
        ],
        "quizQuestion": "",
        "surpriseMessage": "",
        "festivalName": "",
        "audioData": "",
        "videoData": "",
        "audioDataName": "",
        "videoDataName": ""
      },
      "popularity": "popular",
      "templateRole": "customizable-blueprint"
    },
    {
      "slug": "wishora-housewarming-tour",
      "id": "wishora-housewarming-tour",
      "name": "House Tour & Memories",
      "blurb": "A video-first housewarming page for showing the new space to family and friends.",
      "includes": [
        "Cover",
        "Home Welcome",
        "Photos",
        "Timeline",
        "Letter"
      ],
      "occasion": "Housewarming",
      "occasionId": "housewarming",
      "engine": "cinema",
      "variant": "tour",
      "photoLimit": 8,
      "palette": "mint",
      "cover": "images/templates/wishora-housewarming-tour/hero.svg",
      "pages": [
        "cover",
        "dedication",
        "video",
        "photos",
        "home-welcome",
        "timeline",
        "letter",
        "guestbook",
        "surprise",
        "fireworks"
      ],
      "sections": [
        "cover",
        "dedication",
        "video",
        "photos",
        "home-welcome",
        "timeline",
        "letter",
        "guestbook",
        "surprise",
        "fireworks"
      ],
      "defaults": {
        "recipient": "",
        "sender": "",
        "passcode": "",
        "passcodeProtected": true,
        "occasionLabel": "Housewarming",
        "title": "",
        "letter": "",
        "date": "",
        "songTitle": "",
        "songArtist": "",
        "movieTitle": "",
        "movieTagline": "",
        "memories": [],
        "promises": [],
        "photos": [],
        "theme": "mint",
        "sections": [
          "cover",
          "dedication",
          "video",
          "photos",
          "home-welcome",
          "timeline",
          "letter",
          "guestbook",
          "surprise",
          "fireworks"
        ],
        "quizQuestion": "",
        "surpriseMessage": "",
        "festivalName": "",
        "audioData": "",
        "videoData": "",
        "audioDataName": "",
        "videoDataName": ""
      },
      "popularity": "standard",
      "templateRole": "customizable-blueprint"
    },
    {
      "slug": "wishora-festival-wishes-diwali",
      "id": "wishora-festival-wishes-diwali",
      "name": "Diwali Glow",
      "blurb": "A festive Diwali page with family photos, wishes, music and a sparkling celebration.",
      "includes": [
        "Cover",
        "Festival Greeting",
        "Photos",
        "Wishes",
        "Letter"
      ],
      "occasion": "Festival Wishes",
      "occasionId": "festival-wishes",
      "engine": "minisite",
      "variant": "diwali",
      "photoLimit": 6,
      "palette": "lemon",
      "cover": "images/templates/wishora-festival-wishes-diwali/hero.svg",
      "pages": [
        "cover",
        "dedication",
        "festival-greeting",
        "photos",
        "wishes",
        "letter",
        "song",
        "surprise",
        "quiz",
        "fireworks"
      ],
      "sections": [
        "cover",
        "dedication",
        "festival-greeting",
        "photos",
        "wishes",
        "letter",
        "song",
        "surprise",
        "quiz",
        "fireworks"
      ],
      "defaults": {
        "recipient": "",
        "sender": "",
        "passcode": "",
        "passcodeProtected": true,
        "occasionLabel": "Festival Wishes",
        "title": "",
        "letter": "",
        "date": "",
        "songTitle": "",
        "songArtist": "",
        "movieTitle": "",
        "movieTagline": "",
        "memories": [],
        "promises": [],
        "photos": [],
        "theme": "lemon",
        "sections": [
          "cover",
          "dedication",
          "festival-greeting",
          "photos",
          "wishes",
          "letter",
          "song",
          "surprise",
          "quiz",
          "fireworks"
        ],
        "quizQuestion": "",
        "surpriseMessage": "",
        "festivalName": "",
        "audioData": "",
        "videoData": "",
        "audioDataName": "",
        "videoDataName": ""
      },
      "popularity": "standard",
      "templateRole": "customizable-blueprint"
    },
    {
      "slug": "wishora-festival-wishes-family",
      "id": "wishora-festival-wishes-family",
      "name": "Festive Family Story",
      "blurb": "A flexible festive template for New Year, Pongal, Sankranti, Raksha Bandhan and other celebrations.",
      "includes": [
        "Cover",
        "Festival Greeting",
        "Photos",
        "Wishes",
        "Letter"
      ],
      "occasion": "Festival Wishes",
      "occasionId": "festival-wishes",
      "engine": "museum",
      "variant": "family",
      "photoLimit": 8,
      "palette": "lemon",
      "cover": "images/templates/wishora-festival-wishes-family/hero.svg",
      "pages": [
        "cover",
        "dedication",
        "museum",
        "photos",
        "festival-greeting",
        "memories",
        "letter",
        "wishes",
        "guestbook",
        "fireworks"
      ],
      "sections": [
        "cover",
        "dedication",
        "museum",
        "photos",
        "festival-greeting",
        "memories",
        "letter",
        "wishes",
        "guestbook",
        "fireworks"
      ],
      "defaults": {
        "recipient": "",
        "sender": "",
        "passcode": "",
        "passcodeProtected": true,
        "occasionLabel": "Festival Wishes",
        "title": "",
        "letter": "",
        "date": "",
        "songTitle": "",
        "songArtist": "",
        "movieTitle": "",
        "movieTagline": "",
        "memories": [],
        "promises": [],
        "photos": [],
        "theme": "lemon",
        "sections": [
          "cover",
          "dedication",
          "museum",
          "photos",
          "festival-greeting",
          "memories",
          "letter",
          "wishes",
          "guestbook",
          "fireworks"
        ],
        "quizQuestion": "",
        "surpriseMessage": "",
        "festivalName": "",
        "audioData": "",
        "videoData": "",
        "audioDataName": "",
        "videoDataName": ""
      },
      "popularity": "popular",
      "templateRole": "customizable-blueprint"
    },
    {
      "slug": "wishora-custom-blank",
      "id": "wishora-custom-blank",
      "name": "Blank Celebration Canvas",
      "blurb": "Start simple and compose your own page section by section.",
      "includes": [
        "Cover",
        "Photos",
        "Letter",
        "Timeline",
        "Media"
      ],
      "occasion": "Custom Occasion",
      "occasionId": "custom",
      "engine": "minisite",
      "variant": "blank",
      "photoLimit": 10,
      "palette": "lilac",
      "cover": "images/templates/wishora-custom-blank/hero.svg",
      "pages": [
        "cover",
        "dedication",
        "photos",
        "letter",
        "memories",
        "song",
        "video",
        "guestbook",
        "surprise",
        "fireworks"
      ],
      "sections": [
        "cover",
        "dedication",
        "photos",
        "letter",
        "memories",
        "song",
        "video",
        "guestbook",
        "surprise",
        "fireworks"
      ],
      "defaults": {
        "recipient": "",
        "sender": "",
        "passcode": "",
        "passcodeProtected": true,
        "occasionLabel": "Custom Occasion",
        "title": "",
        "letter": "",
        "date": "",
        "songTitle": "",
        "songArtist": "",
        "movieTitle": "",
        "movieTagline": "",
        "memories": [],
        "promises": [],
        "photos": [],
        "theme": "lilac",
        "sections": [
          "cover",
          "dedication",
          "photos",
          "letter",
          "memories",
          "song",
          "video",
          "guestbook",
          "surprise",
          "fireworks"
        ],
        "quizQuestion": "",
        "surpriseMessage": "",
        "festivalName": "",
        "audioData": "",
        "videoData": "",
        "audioDataName": "",
        "videoDataName": ""
      },
      "popularity": "new",
      "templateRole": "customizable-blueprint"
    },
    {
      "slug": "wishora-custom-mixed",
      "id": "wishora-custom-mixed",
      "name": "Anything Goes",
      "blurb": "Mix games, memories, wishes and surprises into one completely personal celebration.",
      "includes": [
        "Cover",
        "Photos",
        "Letter",
        "Timeline",
        "Media"
      ],
      "occasion": "Custom Occasion",
      "occasionId": "custom",
      "engine": "yesno",
      "variant": "mixed",
      "photoLimit": 8,
      "palette": "lilac",
      "cover": "images/templates/wishora-custom-mixed/hero.svg",
      "pages": [
        "cover",
        "dedication",
        "photos",
        "letter",
        "timeline",
        "song",
        "video",
        "quiz",
        "surprise",
        "fireworks"
      ],
      "sections": [
        "cover",
        "dedication",
        "photos",
        "letter",
        "timeline",
        "song",
        "video",
        "quiz",
        "surprise",
        "fireworks"
      ],
      "defaults": {
        "recipient": "",
        "sender": "",
        "passcode": "",
        "passcodeProtected": true,
        "occasionLabel": "Custom Occasion",
        "title": "",
        "letter": "",
        "date": "",
        "songTitle": "",
        "songArtist": "",
        "movieTitle": "",
        "movieTagline": "",
        "memories": [],
        "promises": [],
        "photos": [],
        "theme": "lilac",
        "sections": [
          "cover",
          "dedication",
          "photos",
          "letter",
          "timeline",
          "song",
          "video",
          "quiz",
          "surprise",
          "fireworks"
        ],
        "quizQuestion": "",
        "surpriseMessage": "",
        "festivalName": "",
        "audioData": "",
        "videoData": "",
        "audioDataName": "",
        "videoDataName": ""
      },
      "popularity": "standard",
      "templateRole": "customizable-blueprint"
    }
  ]
};
/* Wishora multi-page experience plans: every template ships with a complete 10-page story. */
(function(){
  const C=window.WISHORA_CATALOG;
  const plans={
    birthday:{
      classic:['cover','cake','dedication','photos','memories','letter','quiz','song','surprise','fireworks'],
      gift:['cover','giftbox','dedication','photos','letter','song','certificate','memories','surprise','fireworks'],
      playful:['cover','yesno','quiz','photos','dedication','letter','memories','song','surprise','fireworks'],
      milestone:['cover','dedication','timeline','museum','photos','certificate','memories','letter','song','fireworks'],
      cinema:['cover','video','dedication','photos','memories','letter','cake','song','surprise','fireworks']
    },
    anniversary:{
      story:['cover','dedication','timeline','photos','memories','letter','fourletters','song','promises','fireworks'],
      vows:['cover','promises','photos','dedication','letter','song','fourletters','certificate','memories','fireworks'],
      cinema:['cover','video','dedication','memories','photos','letter','song','timeline','surprise','fireworks'],
      gift:['cover','giftbox','dedication','photos','letter','certificate','song','memories','promises','fireworks'],
      archive:['cover','museum','timeline','dedication','promises','photos','letter','fourletters','song','fireworks']
    },
    wedding:{
      story:['cover','dedication','photos','timeline','wedding-vows','letter','guestbook','song','video','fireworks'],
      vows:['cover','wedding-vows','dedication','letter','photos','promises','timeline','guestbook','song','fireworks'],
      cinema:['cover','video','dedication','photos','letter','timeline','song','wedding-vows','wishes','fireworks'],
      gift:['cover','giftbox','dedication','wedding-vows','photos','letter','certificate','song','guestbook','fireworks'],
      thanks:['cover','dedication','photos','wedding-vows','letter','guestbook','wishes','song','video','fireworks']
    },
    'baby-shower':{
      welcome:['cover','baby-wishes','dedication','photos','timeline','letter','wishes','countdown','giftbox','surprise'],
      mama:['cover','photos','dedication','timeline','letter','baby-wishes','wishes','song','guestbook','surprise'],
      game:['cover','quiz','dedication','photos','yesno','baby-wishes','letter','wishes','giftbox','surprise'],
      gift:['cover','giftbox','dedication','baby-wishes','photos','letter','timeline','wishes','song','surprise'],
      story:['cover','timeline','dedication','photos','song','letter','baby-wishes','wishes','countdown','surprise']
    },
    graduation:{
      classic:['cover','graduation-diploma','dedication','photos','timeline','letter','certificate','wishes','guestbook','fireworks'],
      cinema:['cover','video','dedication','photos','letter','timeline','graduation-diploma','song','wishes','fireworks'],
      museum:['cover','museum','dedication','timeline','photos','graduation-diploma','letter','certificate','guestbook','fireworks'],
      proud:['cover','letter','graduation-diploma','dedication','photos','song','timeline','certificate','wishes','fireworks'],
      future:['cover','dedication','letter','timeline','countdown','photos','graduation-diploma','video','wishes','fireworks']
    },
    congratulations:{
      celebrate:['cover','congrats-confetti','dedication','photos','letter','certificate','timeline','quiz','giftbox','fireworks'],
      gallery:['cover','museum','dedication','photos','timeline','certificate','letter','guestbook','song','fireworks'],
      news:['cover','newspaper','dedication','letter','photos','timeline','certificate','guestbook','wishes','fireworks'],
      gift:['cover','giftbox','dedication','certificate','letter','photos','timeline','congrats-confetti','surprise','fireworks'],
      modern:['cover','video','dedication','photos','letter','timeline','song','congrats-confetti','certificate','fireworks']
    },
    farewell:{
      voyage:['cover','countdown','dedication','photos','letter','farewell-toast','timeline','wishes','guestbook','fireworks'],
      memory:['cover','museum','dedication','photos','timeline','letter','memories','farewell-toast','guestbook','fireworks'],
      cinema:['cover','video','dedication','photos','letter','memories','song','timeline','farewell-toast','fireworks'],
      gift:['cover','giftbox','dedication','letter','photos','wishes','timeline','guestbook','farewell-toast','fireworks'],
      news:['cover','newspaper','dedication','photos','guestbook','timeline','letter','wishes','farewell-toast','fireworks']
    },
    housewarming:{
      welcome:['cover','home-welcome','dedication','photos','letter','wishes','timeline','song','guestbook','fireworks'],
      story:['cover','home-welcome','dedication','photos','timeline','letter','wishes','guestbook','song','fireworks'],
      tour:['cover','video','home-welcome','photos','timeline','letter','wishes','guestbook','song','fireworks'],
      gift:['cover','giftbox','home-welcome','dedication','photos','letter','timeline','wishes','song','fireworks'],
      cosy:['cover','home-welcome','dedication','photos','letter','song','wishes','guestbook','timeline','fireworks']
    },
    'festival-wishes':{
      diwali:['cover','festival-greeting','dedication','photos','letter','timeline','song','wishes','guestbook','fireworks'],
      christmas:['cover','festival-greeting','dedication','photos','letter','wishes','guestbook','song','video','fireworks'],
      eid:['cover','festival-greeting','dedication','photos','letter','wishes','timeline','guestbook','song','fireworks'],
      holi:['cover','festival-greeting','dedication','photos','guestbook','letter','wishes','song','video','fireworks'],
      family:['cover','festival-greeting','dedication','photos','timeline','letter','wishes','song','guestbook','fireworks']
    },
    custom:{
      blank:['cover','dedication','custom-collage','photos','memories','letter','song','video','guestbook','surprise'],
      scrapbook:['cover','custom-collage','dedication','photos','memories','timeline','letter','song','guestbook','surprise'],
      cinema:['cover','video','dedication','photos','memories','letter','song','timeline','guestbook','surprise'],
      secret:['cover','giftbox','dedication','custom-collage','photos','letter','memories','surprise','guestbook','fireworks'],
      mixed:['cover','yesno','dedication','photos','quiz','timeline','letter','song','guestbook','surprise']
    }
  };
  C.products.forEach(p=>{
    const occasion=plans[p.occasionId];
    const seq=occasion&&occasion[p.variant];
    if(seq&&seq.length>=10){
      p.pages=seq.slice();
      p.sections=seq.slice();
      if(p.defaults){p.defaults.sections=seq.slice();}
    }
  });
})();
