/* Wishora V16 — one unique design skin per template */
(function(){
  const K={};
  const S=(slug,o)=>{K[slug]=o};
  S('wishora-birthday-gift',{f:"'Baloo 2','Trebuchet MS',sans-serif",bg:"radial-gradient(circle,#ffc2de 2px,transparent 3px) 0 0/34px 34px,linear-gradient(160deg,#fff0f7,#fff4cf)",ac:'#ff4f9a',dp:'#c2185b',txt:'#5a2a45',card:'sticker',pop:'balloon',pick:'flip',photo:'polaroid',align:'center',btn:'pill',tr:'zoom',fx:['🎈','🎉','🎁','🍬','✨'],hero:'🎁',gi:'🎁',pi:'🎈',order:['gift','pop','photos','light','pick','letter','wish','surprise','end']});
  S('wishora-anniversary-story',{f:"'Playfair Display',Georgia,serif",bg:"radial-gradient(ellipse at 50% 0,#8a2e4d,transparent 62%),linear-gradient(#2b0f1e,#4d1830)",barc:'#ffd9de',ac:'#e0457b',dp:'#8a2142',txt:'#4a2a35',card:'paper',pop:'petal',pick:'envelope',photo:'frame',align:'left',btn:'outline',tr:'slide',fx:['❤️','🌹','💕','✨','💫'],pi:'❤️',order:['pop','timeline','photos','pick','letter','gift','wish','surprise','end'],tlT:'Our Story',tl:['The day we met','The moment I knew','Today and forever']});
  S('wishora-anniversary-cinema',{f:"'Bebas Neue','Impact',sans-serif",fm:"'Cormorant Garamond',Georgia,serif",bg:"radial-gradient(ellipse at 50% -10%,#7a1020,transparent 55%),linear-gradient(#0b0508,#1a0a10)",barc:'#f5c75b',ac:'#f5c75b',dp:'#f5c75b',txt:'#f3e6d0',sf:'#241418',onsf:'#f3e6d0',card:'film',pop:'ticket',pick:'tile',photo:'film',align:'center',btn:'square',tr:'fade',fx:['🎬','🎞️','🍿','⭐','✨'],hero:'🎬',gi:'🎞️',pi:'🎟️',order:['trailer','pop','photos','pick','letter','gift','wish','surprise','end'],cine:['A story of two people','Years of laughter, one love','Now showing: your anniversary']});
  S('wishora-wedding-story',{f:"'Cormorant Garamond',Georgia,serif",bg:"linear-gradient(160deg,#fdf6ef,#f6e4e4)",ac:'#c9776b',dp:'#8f4a4a',txt:'#5a3a3a',card:'paper',pop:'petal',pick:'envelope',photo:'frame',align:'center',btn:'outline',tr:'fade',order:['pop','light','pick','photos','letter','gift','wish','surprise','end']});
  S('wishora-wedding-vows',{f:"'DM Serif Display',Georgia,serif",fm:"'Inter',system-ui,sans-serif",bg:"linear-gradient(160deg,#eef3ea,#dfe8dc)",ac:'#6f9a78',dp:'#3f5b45',txt:'#2f4535',card:'none',pop:'ring',pick:'tile',photo:'stack',align:'left',btn:'square',tr:'slide',fx:['🌿','🤍','💍','🕊️','✨'],pi:'💍',order:['pop','vows','photos','letter','pick','gift','wish','surprise','end']});
  S('wishora-baby-shower-welcome',{f:"'Baloo 2','Trebuchet MS',sans-serif",bg:"radial-gradient(circle at 18% 16%,#fff 0 34px,transparent 35px),radial-gradient(circle at 84% 70%,#fff 0 46px,transparent 47px),linear-gradient(160deg,#dff3ff,#f2e6ff)",ac:'#4aa3d6',dp:'#2b6b94',txt:'#3d5a73',card:'cloud',pop:'cloud',pick:'flip',photo:'hang',align:'center',btn:'pill',tr:'zoom',order:['pop','light','pick','photos','letter','gift','wish','surprise','end']});
  S('wishora-baby-shower-game',{f:"'Baloo 2','Trebuchet MS',sans-serif",bg:"repeating-linear-gradient(45deg,#fff3b0 0 18px,#ffe27a 18px 36px)",ac:'#ff6b6b',dp:'#1d2b64',txt:'#1d2b64',card:'neo',pop:'bubble',pick:'tile',photo:'stack',align:'center',btn:'neo',tr:'zoom',fx:['🍼','🧸','⭐','🎈','💛'],pi:'🫧',order:['pop','quiz','pick','photos','letter','gift','wish','surprise','end']});
  S('wishora-graduation-classic',{f:"'Playfair Display',Georgia,serif",bg:"linear-gradient(160deg,#16264a,#0b1430)",barc:'#ffe9a8',ac:'#c9a227',dp:'#1c3a8a',txt:'#2b3350',card:'certificate',pop:'star',pick:'tile',photo:'frame',align:'center',btn:'square',tr:'fade',order:['pop','light','pick','photos','letter','gift','wish','surprise','end']});
  S('wishora-graduation-future',{f:"'Space Grotesk',system-ui,sans-serif",bg:"radial-gradient(600px 400px at 85% 0,rgba(0,194,255,.35),transparent),radial-gradient(500px 400px at 0 100%,rgba(168,85,247,.35),transparent),#0a0f24",barc:'#cfe0ff',ac:'#22d3ee',dp:'#e8f3ff',txt:'#cfe0ff',sf:'rgba(255,255,255,.1)',onsf:'#e8f3ff',card:'glass',pop:'orb',pick:'tile',photo:'window',align:'left',btn:'outline',tr:'slide',fx:['🚀','⭐','✨','🌐','💡'],pi:'💡',order:['pop','timeline','photos','pick','letter','gift','wish','surprise','end'],tlT:'The Road Ahead',tl:['First, celebrate','Next, explore','Then, build your dream']});
  S('wishora-congratulations-celebrate',{f:"'Poppins',system-ui,sans-serif",bg:"repeating-conic-gradient(from 0deg at 50% 38%,#ffd36e 0 10deg,#ffb347 10deg 20deg)",ac:'#ff3d7f',dp:'#b8115a',txt:'#4a2040',card:'neo',pop:'coin',pick:'flip',photo:'stack',align:'center',btn:'pill',tr:'zoom',order:['pop','light','pick','photos','letter','gift','wish','surprise','end']});
  S('wishora-congratulations-gallery',{f:"'Cormorant Garamond',Georgia,serif",fm:"'Inter',system-ui,sans-serif",bg:"linear-gradient(#f4f1ea,#e9e4d9)",ac:'#b08d57',dp:'#222',txt:'#444',card:'museum',pop:'plaque',pick:'tile',photo:'frame',align:'left',btn:'square',tr:'fade',order:['pop','photos','pick','letter','gift','wish','surprise','end']});
  S('wishora-farewell-voyage',{f:"'Special Elite','Courier New',monospace",bg:"linear-gradient(180deg,#8fd3f4,#e6f7ff 60%,#f9e6c8)",ac:'#e8590c',dp:'#0e4a63',txt:'#27495a',card:'ticket',pop:'sail',pick:'tile',photo:'tape',align:'left',btn:'square',tr:'slide',gi:'🧳',pi:'⛵',order:['pop','stamp','photos','pick','letter','gift','wish','surprise','end'],st:['New horizons','Old friends','Next adventure']});
  S('wishora-farewell-memory',{f:"'Caveat','Comic Sans MS',cursive",bg:"repeating-linear-gradient(0deg,#f3e3c6 0 28px,#e9d4ae 28px 29px)",ac:'#c26a2e',dp:'#7a4a24',txt:'#5d3b1f',card:'scrap',pop:'leaf',pick:'envelope',photo:'tape',align:'center',btn:'outline',tr:'rise',pi:'🍂',order:['pop','timeline','photos','pick','letter','gift','wish','surprise','end'],tlT:'Memory Lane',tl:['Where it began','Our best day','What I will miss']});
  S('wishora-housewarming-welcome',{f:"'Poppins',system-ui,sans-serif",bg:"repeating-linear-gradient(90deg,#fdeed8 0 38px,#f9e2c0 38px 40px)",ac:'#d9822b',dp:'#8a4b12',txt:'#5d3a1a',card:'arch',pop:'tag',pick:'tile',photo:'window',align:'center',btn:'pill',tr:'slide',gi:'🚪',pi:'🔑',order:['pop','light','pick','photos','letter','gift','wish','surprise','end']});
  S('wishora-housewarming-tour',{f:"'DM Serif Display',Georgia,serif",fm:"'Inter',system-ui,sans-serif",bg:"linear-gradient(rgba(255,255,255,.12) 1px,transparent 1px) 0 0/28px 28px,linear-gradient(90deg,rgba(255,255,255,.12) 1px,transparent 1px) 0 0/28px 28px,#1d4e89",barc:'#dbe9ff',ac:'#ffd166',dp:'#fff',txt:'#dbe9ff',sf:'rgba(255,255,255,.12)',onsf:'#fff',card:'blueprint',pop:'plaque',pick:'tile',photo:'window',align:'left',btn:'outline',tr:'slide',pi:'📐',order:['pop','rooms','photos','pick','letter','gift','wish','surprise','end'],rooms:['Living Room','Kitchen','Garden'],roomc:['Where we gather','Where the magic is cooked','Where the sun lives']});
  S('wishora-festival-wishes-diwali',{f:"'Playfair Display',Georgia,serif",bg:"radial-gradient(circle,rgba(255,179,71,.28) 1.5px,transparent 2px) 0 0/26px 26px,radial-gradient(ellipse at 50% 0,#a63a10,transparent 60%),linear-gradient(#2a0c10,#4e1a12)",barc:'#ffd98a',ac:'#ff9a1f',dp:'#ffd98a',txt:'#ffe8c4',sf:'rgba(255,255,255,.1)',onsf:'#ffe8c4',card:'goldglass',pop:'lantern',pick:'tile',photo:'frame',align:'center',btn:'pill',tr:'fade',order:['pop','light','pick','photos','letter','gift','wish','surprise','end']});
  S('wishora-festival-wishes-family',{f:"'Fraunces',Georgia,serif",bg:"radial-gradient(circle,rgba(255,200,140,.45) 0 30%,transparent 31%) 0 0/60px 60px,linear-gradient(160deg,#fff3dc,#ffe0b8)",ac:'#e8590c',dp:'#9c3a06',txt:'#5c2f12',card:'scallop',pop:'leaf',pick:'envelope',photo:'hang',align:'center',btn:'pill',tr:'rise',pi:'🌼',order:['pop','light','photos','timeline','pick','letter','gift','wish','surprise','end'],tlT:'Family Traditions',tl:['Cleaning & decorating','Lights & sweets','Together at the table']});
  S('wishora-custom-blank',{f:"'Inter',system-ui,sans-serif",bg:"#fafafa",ac:'#111',dp:'#111',txt:'#333',card:'outline',pop:'ring',pick:'tile',photo:'stack',align:'left',btn:'outline',tr:'fade',order:['pop','photos','letter','wish','end']});
  S('wishora-custom-mixed',{f:"'Space Grotesk',system-ui,sans-serif",bg:"radial-gradient(circle at 15% 20%,#ff8fb1 0 110px,transparent 111px),radial-gradient(circle at 85% 30%,#7be0d6 0 130px,transparent 131px),radial-gradient(circle at 50% 92%,#ffd86b 0 150px,transparent 151px),#fff7ec",ac:'#7c5cff',dp:'#2b1d6b',txt:'#33295c',card:'collage',pop:'puzzle',pick:'flip',photo:'stack',align:'center',btn:'neo',tr:'zoom',order:['pop','light','pick','photos','letter','gift','wish','surprise','end']});
  const T={'birthday-gift': {'i': 'A Birthday Surprise', 'ph': 'Birthday Moments', 'lt': 'A Birthday Letter', 'md': 'Birthday Soundtrack', 'su': 'One Last Birthday Surprise'}, 'anniversary-story': {'i': 'Our Love Story', 'ph': 'Our Favourite Moments', 'lt': 'Dear Love', 'md': 'Our Song', 'su': 'Something Just For Us'}, 'anniversary-cinema': {'i': 'The Feature Presentation', 'ph': 'Behind the Scenes', 'lt': 'The Love Letter', 'md': 'Original Soundtrack', 'su': 'Post-Credits Scene'}, 'wedding-story': {'i': 'Our Wedding Story', 'ph': 'Wedding Album', 'lt': 'A Letter to You Both', 'md': 'Our First Dance', 'su': 'One More Blessing'}, 'wedding-vows': {'i': 'Our Vows', 'ph': 'The Day in Pictures', 'lt': 'Words from My Heart', 'md': 'Our Wedding Song', 'su': 'A Final Promise'}, 'baby-shower-welcome': {'i': 'A Little Someone Is Coming', 'ph': 'Baby Bump Moments', 'lt': 'A Note for Baby', 'md': 'Lullaby Time', 'su': 'A Tiny Surprise'}, 'baby-shower-game': {'i': 'Baby Shower Game Time', 'ph': 'Photo Booth', 'lt': 'Advice for the Parents', 'md': 'Party Playlist', 'su': 'Bonus Round'}, 'graduation-classic': {'i': 'Class of Honours', 'ph': 'Graduation Album', 'lt': 'A Letter of Pride', 'md': 'Commencement Song', 'su': 'One Last Honour'}, 'graduation-future': {'i': 'The Future Starts Now', 'ph': 'Throwback Gallery', 'lt': 'Message to Future You', 'md': 'Launch Playlist', 'su': 'Next Mission'}, 'congratulations-celebrate': {'i': 'Time to Celebrate!', 'ph': 'Victory Snapshots', 'lt': 'A Cheer for You', 'md': 'Victory Anthem', 'su': 'Bonus Cheer'}, 'congratulations-gallery': {'i': 'The Exhibition of You', 'ph': 'The Collection', 'lt': 'Curator\u2019s Note', 'md': 'Audio Guide', 'su': 'The Final Exhibit'}, 'farewell-voyage': {'i': 'Boarding Soon', 'ph': 'Postcards From Us', 'lt': 'A Letter for the Journey', 'md': 'Travel Playlist', 'su': 'Last Boarding Call'}, 'farewell-memory': {'i': 'Memories We Made', 'ph': 'Our Scrapbook', 'lt': 'A Goodbye Note', 'md': 'Songs We Shared', 'su': 'One Last Memory'}, 'housewarming-welcome': {'i': 'Welcome Home', 'ph': 'Home Sweet Photos', 'lt': 'A Note for the New Door', 'md': 'House Party Playlist', 'su': 'One More Gift'}, 'housewarming-tour': {'i': 'House Tour Time', 'ph': 'Gallery Walls', 'lt': 'A Note on the Fridge', 'md': 'Background Music', 'su': 'The Secret Room'}, 'festival-wishes-diwali': {'i': 'A Festival of Lights', 'ph': 'Festive Moments', 'lt': 'A Letter of Blessings', 'md': 'Festival Music', 'su': 'One More Diya'}, 'festival-wishes-family': {'i': 'Our Family Festival', 'ph': 'Family Album', 'lt': 'A Letter to the Family', 'md': 'Festive Songs', 'su': 'A Family Surprise'}, 'custom-blank': {'i': 'Something for You', 'ph': 'Photos', 'lt': 'A Note', 'md': 'Audio', 'su': 'One More Thing'}, 'custom-mixed': {'i': 'A Mixed-Up Surprise', 'ph': 'Mixed Moments', 'lt': 'A Letter', 'md': 'A Mix Tape', 'su': 'Plot Twist'}};
  Object.keys(T).forEach(k=>{if(K['wishora-'+k])K['wishora-'+k].T=T[k]});
  window.WISHORA_SKINS=K;
})();
