window.WISHORA_SECTIONS = [
  {id:'dedication', icon:'✦', name:'Dedication', description:'A personalized page explaining why this celebration exists'},
  {id:'cover', icon:'✦', name:'Cover', description:'Beautiful opening screen'},
  {id:'letter', icon:'✎', name:'Letter', description:'Your personal message'},
  {id:'photos', icon:'▧', name:'Photo Gallery', description:'Your favorite photos'},
  {id:'memories', icon:'◷', name:'Memory Timeline', description:'Moments in order'},
  {id:'song', icon:'♪', name:'Our Song', description:'Add a song or audio'},
  {id:'video', icon:'▶', name:'Video', description:'Add a personal video'},
  {id:'giftbox', icon:'◇', name:'Gift Box', description:'Tap to reveal a surprise'},
  {id:'yesno', icon:'?', name:'Yes / No', description:'Playful interactive question'},
  {id:'timeline', icon:'↗', name:'Story Timeline', description:'Tell the story in chapters'},
  {id:'promises', icon:'♡', name:'Promises', description:'Promises, wishes or notes'},
  {id:'certificate', icon:'□', name:'Certificate', description:'A fun personalized award'},
  {id:'wishes', icon:'✧', name:'Wish Wall', description:'Celebrate with wishes'},
  {id:'countdown', icon:'◴', name:'Countdown', description:'Count toward a special date'},
  {id:'fireworks', icon:'✹', name:'Celebration', description:'Confetti and fireworks'},
  {id:'quiz', icon:'☷', name:'Mini Quiz', description:'A little interactive game'},
  {id:'fourletters', icon:'L', name:'Four Letters', description:'Open hidden messages'},
  {id:'newspaper', icon:'▤', name:'Special Edition', description:'A personalized digital newspaper'},
  {id:'museum', icon:'⌂', name:'Museum', description:'Curate your memories'},
  {id:'proposal', icon:'♡', name:'Big Question', description:'A cinematic reveal'},
  {id:'guestbook', icon:'☏', name:'Guestbook', description:'Leave notes and wishes'},
  {id:'surprise', icon:'!', name:'Surprise Reveal', description:'Hide something until the right moment'},
  {id:'wedding-vows', icon:'💍', name:'Wedding Vows', description:'Vows, blessings and ceremony words', occasions:['wedding']},
  {id:'baby-wishes', icon:'🧸', name:'Baby Wishes', description:'Wishes for the little one and parents', occasions:['baby-shower']},
  {id:'graduation-diploma', icon:'🎓', name:'Graduation Diploma', description:'A custom achievement certificate', occasions:['graduation']},
  {id:'congrats-confetti', icon:'🎊', name:'Achievement Toast', description:'A celebration card for the big win', occasions:['congratulations']},
  {id:'farewell-toast', icon:'💐', name:'Farewell Toast', description:'Goodbye words and wishes for the journey', occasions:['farewell']},
  {id:'home-welcome', icon:'🏡', name:'Home Welcome', description:'A warm new-home welcome message', occasions:['housewarming']},
  {id:'festival-greeting', icon:'🪔', name:'Festival Greeting', description:'Occasion-aware festive wishes', occasions:['festival-wishes']},
  {id:'custom-collage', icon:'✦', name:'Freeform Collage', description:'A flexible mixed-media section', occasions:['custom']}
];
